services:

  ui:
    build:
      context: ./ui_dsl
      dockerfile: Dockerfile
    container_name: procedure-ui
    environment:
      - LLM_SERVICE_URL=http://extractor:8001
    volumes:
      - ./ui_dsl/src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - extractor

  extractor:
    build:
      context: ./extractor_pipeline
      dockerfile: Dockerfile
    container_name: procedure-extractor
    runtime: nvidia
    environment:
      - HF_HOME=/app/src/models/cache
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./extractor_pipeline/src:/app/src
    ports:
      - "8001:8001"
