services:
  rag-app:
    build:
      dockerfile: Dockerfile
      context: .

    container_name: rag-app

    runtime: nvidia

    environment:
      - HF_HOME=/app/src/models/cache
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    volumes:
      - ./src:/app/src
      - ./src/config:/app/src/config
      - ./src/models:/app/src/models
      - ./src/document_processor:/app/src/document_processor
      - ./src/input_files:/app/src/input_files
      - ./src/vectorstore:/app/src/vectorstore
      - ./src/rag:/app/src/rag

    ports:
      - "8000:8000"

